baseURL = "https://cheshire.io/"
languageCode = "en-us"
theme = "hugo-ink"
title = "Victor Neo"

copyright = "CC BY-NC-SA 4.0"

[params]
        subtitle = "Python, Django and English Breakfast Tea. Engineering @ Carousell"

	# Optional 64x64 avatar image.
	avatar = "/images/photo.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/victorneo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/victorneo"
